[package]
name = "multicast_relay"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
clap = { version = "4.5.8", features = ["derive"] }
libc = "0.2.155"
metrics = "0.22.0"
metrics-exporter-prometheus = "0.13.1"
pnet = "0.34.0"
privdrop = "0.5.1"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.120"
socket2 = { version = "0.5.7", features = ["all"] }
sysinfo = "0.30.12"
tokio = { version = "1.38.0", features = ["full"] }
tokio-uring = "0.5.0"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
uuid = { version = "1.9.1", features = ["v4"] }

[dev-dependencies]
predicates = "3.1.0"

[features]
integration_test = []

[[bin]]
name = "poc_closure_ownership"
path = "experiments/poc_closure_ownership.rs"

[[bin]]
name = "closure_passing_test"
path = "experiments/closure_passing_test.rs"
required-features = ["integration_test"]

[[bin]]
name = "multicast_relay"
path = "src/main.rs"

[[bin]]
name = "traffic_generator"
path = "src/traffic_generator.rs"

[[bin]]
name = "control_client"
path = "src/control_client.rs"