[target.aarch64-unknown-linux-gnu]
linker = "/home/acooks/pigeon/scripts/aarch64-linux-gnu-gcc-wrapper.sh"
rustflags = ["-C", "link-arg=--sysroot=/usr/aarch64-redhat-linux/sys-root/fc42"]

[target.aarch64-unknown-linux-musl]
linker = "aarch64-linux-gnu-gcc"

[source.crates-io]
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "/home/acooks/rust-toolchain/vendor"
